#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:nil arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:t
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:nil todo:t |:t 
#+TITLE: Add more intelligent shortcut keys to outliner <draft>
#+DATE: <2019-03-31 21:31 Sun>
#+AUTHOR: Yadong Cheung
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+OPTIONS: html-link-use-abs-url:nil html-postamble:auto
#+OPTIONS: html-preamble:t html-scripts:t html-style:t
#+OPTIONS: html5-fancy:nil tex:t
#+HTML_DOCTYPE: xhtml-strict
#+HTML_CONTAINER: div
#+DESCRIPTION:Apply for Blender of GSoC 2019
#+KEYWORDS:GSoC Blender
#+HTML_LINK_HOME:
#+HTML_LINK_UP:
#+HTML_MATHJAX:
#+HTML_HEAD:
#+HTML_HEAD_EXTRA:
#+SUBTITLE: Proposal.pdf would be written in $\LaTeX$
#+INFOJS_OPT:
#+CREATOR: <a href="https://www.gnu.org/software/emacs/">Emacs</a> 26.1 (<a href="https://orgmode.org">Org</a> mode 9.2)
#+LATEX_HEADER:


* Name
Yadong Cheung 张亚栋

* Contact
*Email:*

zhyd007@gmail.com

10154508169@stu.ecnu.edu.cn

*IRC nick:* Cheung

* Synopsis
  For artists, keyboard shortcuts may more convenient than buttons clicking, and most of all features can be implemented, such
 as "open files /<Ctrl+O>/", but there are some important features we need shortcuts, for example, to select all items 
in-between, we  must click all one. 
The project is designed to add more intelligent shortcuts to improve outliner.

* Benefits
  More user-friendly and powerful outliner.

* Deliverables
** Improvement User Experience of Outliner.
   - Enter /<Del>/ to delete object.
   - Click the object you want to choose, press /<Shift>/ and click the last one you want, you will choose all between them.
   - Click the first item you want to choose, press /<Ctrl>/ and click other ones, you can choose them and ignore the other between them.
   - Add a component "Synced Selection".
* Project Details [3/6]
  *code layout*: /space_outliner --> interface --> object --> windowmanager/ \\
  The major code is in /source/blender/editors// *space_outliner* && *space_view3d*
 path.\\
  - [X] Shortcut keys for operations.\\
    *wm_keymap.c* defines keymap and includes *wm_event_types.h*, which contains /keyboard codes./
  - [X] Sync selection between 3D viewport and outliner.\\
    We only need one way to show selections - the highlighted row.
  - [X] Shift-select to select a range of items.\\
    It is related to the *tree's traversal* problem, and shortcut keys binding.
  - [ ] Box selection by simple click and drag.\\  
  - [ ] Arrow key navigation.
  - [ ] More consistent and powerful right-click menus.
* Project Schedule
  I could finish this project in 12 weeks and about 1 item per 2 weeks. (more details...)

* Bio
  My name is Yadong Cheung, I live in China.
Currently studying at East China Normal University(ECNU).
I major in preschool education, UI design is my hobby, and I love 3D modules especially in animals.
The first time that I know CG is the interdisciplinary course /The Film and Television Direct/ 
I studied, which needed special effects modeling. HTML and CSS are based on web and it's designed for
front-end engineer, maybe they could be helpful of outliner designing, I also started learning $\TeX$, the perfect
typesetting system, last year. 

** Programming experience
I like *C* language, and although I have no experience in products but I read the two books which are known as
 *The C Programming Language* /2e/ and
*C Primer Plus* /6e/. I used to programme in XCode and Eclipse.
I learned *Python* from edx, which course is
 [[https://www.edx.org/course/introduction-to-computer-science-and-programming-using-python-0][Introduction to Computer Science and Programming Using Python]].
